name: Checks
on: [ push ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependecies
      run: yarn
    - name: Build
      run: yarn build
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependecies
      run: yarn
    - name: Tests
      run: yarn test
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependecies
      run: yarn
    - name: Lint
      run: yarn lint
